In [19]:
import openml
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import ShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [20]:
datasets = openml.datasets.list_datasets()
df_datasets = pd.DataFrame(datasets).transpose()
suitable_datasets = df_datasets[(df_datasets['NumberOfInstances'] > 5000) & 
                                (df_datasets['NumberOfInstances'] < 30000) &
                                (df_datasets['NumberOfClasses'] > 2)]
# Print some suitable datasets to choose from
print(suitable_datasets[['name', 'NumberOfInstances', 'NumberOfClasses']])


C:\Users\powar\AppData\Local\Temp\ipykernel_24492\3008110783.py:1: FutureWarning: Support for `output_format` of 'dict' will be removed in 0.15 and pandas dataframes will be returned instead. To ensure your code will continue to work, use `output_format`='dataframe'.
  datasets = openml.datasets.list_datasets()


                                                 name NumberOfInstances  \
6                                              letter           20000.0   
26                                            nursery           12960.0   
28                                          optdigits            5620.0   
30                                        page-blocks            5473.0   
32                                          pendigits           10992.0   
...                                               ...               ...   
45919      padding-attack-dataset-facebook-2023-12-05           19487.0   
45920  padding-attack-dataset-netscalergcm-2023-12-13            7678.0   
45921         padding-attack-dataset-panos-2023-12-13            7869.0   
45923                                    IndoorScenes           15620.0   
45936                                    IndoorScenes           15620.0   

      NumberOfClasses  
6                26.0  
26                5.0  
28               10.0  
30 

In [21]:
dataset_id = 45919  # Replace with the actual ID after checking
data = fetch_openml(data_id=dataset_id, as_frame=True)
X = data.data
y = data.target

c:\Program Files\Python38\lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [22]:
from sklearn import svm
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import random as r
     

In [23]:
best_accuracy = 0
best_kernel = ""
best_nu = 0
best_epsilon = 0
iteration = 100
kernel_list = [ 'sigmoid', 'rbf', 'poly', 'linear']

In [24]:
def fitness_function(x_train, y_train, x_test, y_test, C, kernel, gamma):
    model = svm.SVC(C=C, kernel=kernel, gamma=gamma)
    model.fit(x_train, y_train)
    predicted = model.predict(x_test)
    accuracy = accuracy_score(y_test, predicted) * 100
    return accuracy


In [25]:
num_samples = 10
sample_indices = np.array_split(np.random.permutation(len(X)), num_samples)

best_accuracy_list = []
best_params_list = []
sample_indices

[array([14425,  6042,  4970, ..., 10708, 18185,  7080]),
 array([ 4603,  9100,  8624, ..., 15440, 12384,  8225]),
 array([  437, 15503, 13613, ...,   949,  9363,  2286]),
 array([ 6229,  2153,  4159, ...,  2489, 10121,  7355]),
 array([ 7127, 19120,   691, ...,  5298,  2326,  6076]),
 array([11297,  6779, 12249, ...,  5663, 18218,  3029]),
 array([ 9043, 12605, 13782, ...,  8968, 15842,  7394]),
 array([ 3012,  4481,  2627, ...,  6106, 18847,  4332]),
 array([ 8771,  7492, 17850, ..., 16457, 17782, 12467]),
 array([ 9689,  5337,  4703, ...,  3578, 19366,  2052])]

In [26]:
for indices in sample_indices:
    X_train, X_test, y_train, y_test = train_test_split(X.iloc[indices], y.iloc[indices], test_size=0.3, random_state=42)

    best_accuracy = 0
    best_params = {'C': 0, 'kernel': '', 'gamma': 0}

    for j in range(iteration):
        C = np.random.uniform(0.1, 10)
        kernel = np.random.choice(kernel_list)
        gamma = np.random.uniform(0,10)

        try:
            accuracy = fitness_function(X_train, y_train, X_test, y_test, C, kernel, gamma)
        except ValueError:
            continue

        if accuracy > best_accuracy:
            best_params = {'C': C, 'kernel': kernel, 'gamma': gamma}
            best_accuracy = accuracy

    best_accuracy_list.append(best_accuracy)
    best_params_list.append(best_params)

In [27]:
plt.plot(range(1, iteration + 1), best_accuracy_list[max_accuracy_idx], label='Max Accuracy')
plt.xlabel('Iteration')
plt.ylabel('Accuracy')
plt.title('Convergence Graph (Max Accuracy)')
plt.legend()
plt.show()


NameError: name 'max_accuracy_idx' is not defined